### ISSUE TITLE
Can not generate metal shader.

### ISSUE THREAD

**Issue by minggo** [cocos2d/glsl-optimizer#4]
It is strange that, the same GLSL shader can not be converted to metal shader sometimes. The usage of glsl-optimizer codes is [here](https://github.com/minggo/new-renderer/blob/metal-support/src/backend/metal/ShaderModuleMTL.mm#L13).

I think it is because some parameters are not initialized, so it works sometimes.

**Comment by Mee-gu** [comment]
it is a memory issue, you can not use the memory that has already been freed at line36 and 38 in ShaderModuleMTL.mm.

**Comment by minggo** [comment]
Yep, good catch.
